---
title: "Descriptive Statistics Report"
author: "Anna Buchnowska"
date: "7 grudnia 2016"
output:
  pdf_document: 
    fig_caption: yes
    fig_height: 3
    fig_width: 3.5
    keep_tex: yes
    toc: yes
---

```{r setup, include=FALSE}
library(psych)
knitr::opts_chunk$set(echo = FALSE)
```


# Introduction

Following output is generated by RStudio

## Tasks

* **descriptive statistics**
* **modalnosc rozkładów**
* **sprawdzenie czy dane mają rozkład normalny**
* **histogramy**
* **skrzynka z wąsami**
* **powtórzyć zadanie dla zmiennych grupujących**

# Descriptive Statistics
```{r}
data <- read.csv('../oceny.csv', header = TRUE, sep=';')
data$oceny <- as.numeric(gsub(",", ".", data$oceny))
mydata <- as.table(summary(data))
mydata
```


# Histogram
```{r}
hist(data$oceny,
     main="Histogram for Oceny",
     xlab="Oceny",
     xlim = c(2,5),
     breaks = 5)

hist(data$iloraz_intelig,
     main="Histogram for iloraz_intelig")

```




